//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartWCFClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cart", Namespace="http://schemas.datacontract.org/2004/07/ShopingCart")]
    [System.SerializableAttribute()]
    public partial class Cart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Item_PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Name {
            get {
                return this.Item_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_NameField, value) != true)) {
                    this.Item_NameField = value;
                    this.RaisePropertyChanged("Item_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Item_Price {
            get {
                return this.Item_PriceField;
            }
            set {
                if ((object.ReferenceEquals(this.Item_PriceField, value) != true)) {
                    this.Item_PriceField = value;
                    this.RaisePropertyChanged("Item_Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProdCart", ReplyAction="http://tempuri.org/IService1/AddProdCartResponse")]
        string AddProdCart(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddProdCart", ReplyAction="http://tempuri.org/IService1/AddProdCartResponse")]
        System.Threading.Tasks.Task<string> AddProdCartAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartRecords", ReplyAction="http://tempuri.org/IService1/GetCartRecordsResponse")]
        System.Data.DataSet GetCartRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCartRecords", ReplyAction="http://tempuri.org/IService1/GetCartRecordsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCartRecordsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecords", ReplyAction="http://tempuri.org/IService1/DeleteRecordsResponse")]
        string DeleteRecords(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteRecords", ReplyAction="http://tempuri.org/IService1/DeleteRecordsResponse")]
        System.Threading.Tasks.Task<string> DeleteRecordsAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCartRecord", ReplyAction="http://tempuri.org/IService1/SearchCartRecordResponse")]
        System.Data.DataSet SearchCartRecord(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchCartRecord", ReplyAction="http://tempuri.org/IService1/SearchCartRecordResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SearchCartRecordAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCart", ReplyAction="http://tempuri.org/IService1/UpdateCartResponse")]
        string UpdateCart(ShoppingCartWCFClient.ServiceReference1.Cart cart);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateCart", ReplyAction="http://tempuri.org/IService1/UpdateCartResponse")]
        System.Threading.Tasks.Task<string> UpdateCartAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ShoppingCartWCFClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ShoppingCartWCFClient.ServiceReference1.IService1>, ShoppingCartWCFClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddProdCart(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.AddProdCart(cart);
        }
        
        public System.Threading.Tasks.Task<string> AddProdCartAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.AddProdCartAsync(cart);
        }
        
        public System.Data.DataSet GetCartRecords() {
            return base.Channel.GetCartRecords();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCartRecordsAsync() {
            return base.Channel.GetCartRecordsAsync();
        }
        
        public string DeleteRecords(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.DeleteRecords(cart);
        }
        
        public System.Threading.Tasks.Task<string> DeleteRecordsAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.DeleteRecordsAsync(cart);
        }
        
        public System.Data.DataSet SearchCartRecord(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.SearchCartRecord(cart);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SearchCartRecordAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.SearchCartRecordAsync(cart);
        }
        
        public string UpdateCart(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.UpdateCart(cart);
        }
        
        public System.Threading.Tasks.Task<string> UpdateCartAsync(ShoppingCartWCFClient.ServiceReference1.Cart cart) {
            return base.Channel.UpdateCartAsync(cart);
        }
    }
}
